# Frontend Dockerfile for SABDE
FROM node:18-alpine as build

# Set working directory
WORKDIR /app

# Accept build arguments
ARG REACT_APP_API_BASE_URL
ARG REACT_APP_API_BASE_URL_CONTAINER
ARG REACT_APP_API_RESEARCH_GENERATE
ARG REACT_APP_API_RESEARCH_ASYNC
ARG REACT_APP_API_RESEARCH_STATUS
ARG REACT_APP_API_RESEARCH_RESULT
ARG REACT_APP_API_RESEARCH_ENTITIES
ARG REACT_APP_API_RESEARCH_PATHS
ARG REACT_APP_FRONTEND_PORT
ARG REACT_APP_FRONTEND_HOST
ARG REACT_APP_ENVIRONMENT

# Set environment variables for build
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL_CONTAINER=$REACT_APP_API_BASE_URL_CONTAINER
ENV REACT_APP_API_RESEARCH_GENERATE=$REACT_APP_API_RESEARCH_GENERATE
ENV REACT_APP_API_RESEARCH_ASYNC=$REACT_APP_API_RESEARCH_ASYNC
ENV REACT_APP_API_RESEARCH_STATUS=$REACT_APP_API_RESEARCH_STATUS
ENV REACT_APP_API_RESEARCH_RESULT=$REACT_APP_API_RESEARCH_RESULT
ENV REACT_APP_API_RESEARCH_ENTITIES=$REACT_APP_API_RESEARCH_ENTITIES
ENV REACT_APP_API_RESEARCH_PATHS=$REACT_APP_API_RESEARCH_PATHS
ENV REACT_APP_FRONTEND_PORT=$REACT_APP_FRONTEND_PORT
ENV REACT_APP_FRONTEND_HOST=$REACT_APP_FRONTEND_HOST
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built application
COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port
EXPOSE 3000

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
